### ISSUE TITLE
Fonts don't work when building with Cairo on Windows

### ISSUE THREAD

**Issue by blackhole89** [NanoMichael/cLaTeXMath#10]
When building with the Cairo graphics backend under Windows (using msys2-mingw64, which seems to be the best solution for porting a Gtk+ 3 application to Windows at the moment), all fonts fall back to the default `sans` font (so no math symbols render correctly, etc.) This is because `Cairo::select_font_face` always uses the "system default" font selector, which is the native win32 mechanism when building under Windows, but `Font_cairo` loads fonts by making them visible to fontconfig only.

I have a solution to this that stores a `Cairo::FtFontFace` object inside `Font_cairo` and loads it using `Cairo::set_font_face`, and can make a PR if you are interested. I haven't tested it that extensively though, and you might want pick a different approach.

**Comment by NanoMichael** [comment]
@blackhole89 Any PR is appreciated! I'm waiting for your PR :grinning:

**Comment by NanoMichael** [comment]
The `gdi_win` could be removed at compile time if porting the Gtk+ 3 to Windows but can be reserved as a demo to show how to implement the Win32 version.

**Comment by blackhole89** [comment]
Well, I built with __linux__ defined manually; it doesn't seem like msys2 even contains gdi+ headers. (My use case ultimately involves [rendering to a Cairo surface](https://github.com/blackhole89/notekit/blob/master/imagewidgets.cpp#L139), so doing any rendering with GDI would be annoying anyway.)

**Comment by NanoMichael** [comment]
OK, I have the plan to port the Gtk+ 3 to Windows and macOS, so the annoying macros `__OS_Linux__` / `__OS_Windows__` / ... can be removed.
