### ISSUE TITLE
Could TinyTeX::setDefault{Math,Main}Font check if a font actually exists?

### ISSUE THREAD

**Issue by sp1ritCS** [NanoMichael/cLaTeXMath#106]
Currently, it accepts any string and only throws an error in the `TinyTeX::parse` invocation. 

For now, I could work around it with `FontContext::select{Math,Main}Font` (https://github.com/sp1ritCS/notekit/blob/d7e92fff7f634a3c3ef0ce3f20757fcba68b41e2/mainwindow.cpp#L48) however I don't see a reason why the `TinyTeX::setDefault{Math,Main}Font` invocation could do so for me.

**Comment by NanoMichael** [comment]
What do you think if the API design is like this:

```C++
// return false if no math font was found by given name, and the function takes no effect, and no
// exceptions will be thrown
bool setDefaultMathFont(const std::string& name);
```

**Comment by sp1ritCS** [comment]
that'd work

**Comment by NanoMichael** [comment]
done by #111
