### ISSUE TITLE
Security and implementation

### ISSUE THREAD

**Issue by lazingor** [NanoMichael/cLaTeXMath#12]
This project looks awesome! I was wondering: can one get an overview of how much of LaTeX it implements? Is it based on some other implementation? Are all the LaTeX commands it supports in one and the same file, or are they spread out?

Second question: are there any security implications from using this library? Does it allow any shell escaping or system calls, or that kind of thing? I know TeX is its own programming language and has commands like `\input`.

**Comment by NanoMichael** [comment]
> can one get an overview of how much of LaTeX it implements? 

Currently not. I'm planning to make a table to show supported commands. 

> Is it based on some other implementation? Are all the LaTeX commands it supports in one and the same file, or are they spread out?

This project implemented based on the TeX algorithm (part of it, the primitive `\def`, `\xdef` are not supported now), no other dependencies required. You can check the directory `src/core` out.

> are there any security implications from using this library?

Honestly, I'm not 100% sure, but any suggestions are appreciated.
