### ISSUE TITLE
Size of math within \text in context with modified font size

### ISSUE THREAD

**Issue by lazingor** [NanoMichael/cLaTeXMath#16]
This is extremely low priority, but you might be interested. I noticed that font sizing of encapsulated math within a `\text` does not respect the sizing of the context. Take for example
`x^{\text{a $n$}} \sum_{\substack{k \geq 0 \\ j \geq 0 \\ \text{and $k > j$}}} f(k,j)`
The "a" and the "and" are rendered in the correct, smaller size, but the math within the `\text` is rendered at regular size.

I attach screenshots from the project demo and from latex.

cLaTeXMath: 
![mathInText](https://user-images.githubusercontent.com/50640887/80725780-d6047300-8b03-11ea-9854-e1e953f338f1.png)

LaTeX: 
![mathInTextLaTeX](https://user-images.githubusercontent.com/50640887/80725783-d735a000-8b03-11ea-9b83-10d028e4a086.png)

**Comment by NanoMichael** [comment]
The math environment is the default for this project, this issue may be related it, I'll check it soon.
