### ISSUE TITLE
Dynamic version of libmicrotex-qt.dll don't build over MinGW (Openmath branch)

### ISSUE THREAD

**Issue by Jurik-Phys** [NanoMichael/cLaTeXMath#180]
Linker error when build dynamic version of libmicrotex-qt.dll with MinGW 

The latest commit in the openmath branch is currently 086f4eb

To reproduce the error run next command into MSYS2 UCRT64 Shell

1. Clone repository 
   `git clone https://github.com/NanoMichael/MicroTeX.git`
 
2. Change branch to openmath
  ` git checkout --track origin/openmath`

3. Create build directory and move into it
  ` mkdir build; cd ./build`

4. Prepare Makefiles (Default is dynamic library)
  `cmake -DQT=ON ..`

5. Build library
  `cmake --build . -j8`

6. Take error
>  [ 97%] Built target microtex
> [ 98%] Linking CXX shared library libmicrotex-qt.dll
C:/opt/MSYS64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/opt/MSYS64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/libgcc_eh.a(unwind-seh.o):(.text+0x3b0): multiple definition of `_Unwind_Resume'; ../../lib/libmicrotex.dll.a(libmicrotex_dll_d000015.o):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
make[2]: *** [platform/qt/CMakeFiles/microtex-qt.dir/build.make:101: platform/qt/libmicrotex-qt.dll] Error 1
make[1]: *** [CMakeFiles/Makefile2:142: platform/qt/CMakeFiles/microtex-qt.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

The workaround is to build a static library
4''. Prepare Makefiles (Static library with Qt example application)
  `cmake  cmake -DQT=ON -DBUILD_STATIC=ON -DBUILD_EXAMPLE_QT=ON ..`

5''. Build library
  `cmake --build . -j8`
> [ 98%] Linking CXX executable microtex-qt-example.exe
> [100%] Built target microtex-qt-example

6''. Change directory with example application
     ` cd example/qt/`

7''. Run example application
    `./microtex-qt-example`
> Required arguments:
>   <clm data file\>
>   <math font file\>
>   <samples file``\>
Optional arguments:
>   <if render glyph use path: true|false>
>   <if render use skia: true|false>

7''. Run with needed arguments
    ` ./microtex-qt-example ../../res/firamath/FiraMath-Regular.clm2 ../../res/firamath/FiraMath-Regular.otf ../../res/SAMPLES.tex
`
![Openmath-branch-Qt6-Win10-FiraMath-Static](https://github.com/user-attachments/assets/994712b2-4b29-42b1-a756-eb52b6065ec0)

**Comment by sp1ritCS** [comment]
From:
```
C:/opt/MSYS64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/opt/MSYS64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/libgcc_eh.a(unwind-seh.o):(.text+0x3b0): multiple definition of `_Unwind_Resume'; ../../lib/libmicrotex.dll.a(libmicrotex_dll_d000015.o):(.text+0x0): first defined here
```

the issue is probalby that `libmicrotex-qt.dll` attemts to statically link the `libmicrotex.dll.a` instead dynamically linking against `libmicrotex.dll`.

Have you tried using meson instead?

**Comment by Jurik-Phys** [comment]
> Have you tried using meson instead?

Tried it now. Out of the box, meson build system doesn't support Qt6, `example/qt/meson.build` and `platform/qt/meson.build` contain only Qt5 dependencies. Manual changed qt5 to qt6 and run build, but no success. Build system doesn't see part of Qt6 `QMap: No such file or directory`.

> Found ninja-1.11.1 at C:\opt\MSYS64\mingw64\bin/ninja.EXE
> Cleaning... 0 files.

> [1/9] Generating 'platform/qt/libmicrotex-qt-1.dll.p/moc_graphic_qt.cpp' ../platform/qt/graphic_qt.h: note: No relevant classes found. No output generated.
> [3/9] Compiling C++ object platform/qt/libmicrotex-qt-1.dll.p/graphic_qt.cpp.obj
FAILED: platform/qt/libmicrotex-qt-1.dll.p/graphic_qt.cpp.obj
"c++" "-Iplatform/qt/libmicrotex-qt-1.dll.p" "-Iplatform/qt" "-I../platform/qt" "-Ilib" "-I../lib" "
-IC:/opt/Qt/6.6.2/mingw_64/include" "-IC:/opt/Qt/6.6.2/mingw_64/include/QtGui" "-fdiagnostics-color=
always" "-D_GLIBCXX_ASSERTIONS=1" "-D_FILE_OFFSET_BITS=64" "-std=c++17" "-O3" "-DQT_GUI_LIB" -MD -MQ
 platform/qt/libmicrotex-qt-1.dll.p/graphic_qt.cpp.obj -MF "platform/qt/libmicrotex-qt-1.dll.p/graph
ic_qt.cpp.obj.d" -o platform/qt/libmicrotex-qt-1.dll.p/graphic_qt.cpp.obj "-c" ../platform/qt/graphi
c_qt.cpp
In file included from ../platform/qt/graphic_qt.cpp:1:
../platform/qt/graphic_qt.h:6:10: fatal error: QMap: No such file or directory
    6 | #include <QMap>
      |          ^~~~~~
compilation terminated.
> [4/9] Linking target lib/libmicrotex-1.dll
ninja: build stopped: subcommand failed.

**Comment by sp1ritCS** [comment]
> Build system doesn't see part of Qt6 QMap: No such file or directory .

Hmm not sure, but mind trying adding 'Core' to the qt modules in the meson file?

**Comment by Jurik-Phys** [comment]
I found the cause of the error on Stackoverflow [Mingw multiple definition of _Unwind_resume](https://stackoverflow.com/questions/11267877/mingw-multiple-definition-of-unwind-resume). Previously, I compiled Qt library and MicroTeX library & example with `-static-libgcc -static-libstdc++`. Without this compilation flag the MicroTeX library and example compile successfully with CMake.

After the build, I put in one directory next files:
- microtex-qt-example.exe;
- libmicrotex-qt.dll;
- libmicrotex.dll;
- FiraMath-Regular.clm2;
- FiraMath-Regular.otf;
- SAMPLES.tex.

Run examples as  `./microtex-qt-example.exe FiraMath-Regular.clm2 FiraMath-Regular.otf SAMPLES.tex`. **All work!**

**Meson build system**
> Hmm not sure, but mind trying adding 'Core' to the qt modules in the meson file?

After added 'Core' modules into `platform/qt/meson.build` and compile without `-static-libgcc -static-libstdc++` examples and library successful build, but example application silence closes after run.

Build command:
>  ninja -C build
ninja: Entering directory `build'
[61/85] Generating 'platform/qt/libmicrotex-qt-1.dll.p/moc_graphic_qt.cpp'
../platform/qt/graphic_qt.h: note: No relevant classes found. No output generated.
[85/85] Linking target platform/gdi_win/libmicrotex-gdi-1.dll

After the build, I put in one directory next files:
- microtex-qt-example.exe;
- libmicrotex-qt-1.dll;
- libmicrotex-1.dll;

Run microtex-qt-example.exe silence closes:
> $ ls
> libmicrotex-1.dll  libmicrotex-qt-1.dll  microtex-qt-example.exe  microtex-qt-example.exe.p
>
> User.PC@APP-BUILDER UCRT64 ~/Development/tst/MicroTeX/build/example/qt
> $ ./microtex-qt-example.exe
>
> User.PC@APP-BUILDER UCRT64 ~/Development/tst/MicroTeX/build/example/qt

**Comment by Jurik-Phys** [comment]
Compile library and example from openmath branch is successful after remove `-static-libgcc -static-libstdc++` from LDFLAGS

**Comment by sp1ritCS** [comment]
> Run microtex-qt-example.exe silence closes

On windows this is commonly due to missing dlls. Either attempt to double-click the exe from explorer, then it should show a message box telling you which dll is missing or run ldd on the binary.

I'd assume that one of the mingw libgcc_s or libstdc++ is missing

**Comment by Jurik-Phys** [comment]
> I'd assume that one of the mingw libgcc_s or libstdc++ is missing

Strange, but after rolling back the state of the virtual machine and repeating the steps associated with building the project using Meson. All work!!! 

> $ ls
> libmicrotex-1.dll  libmicrotex-qt-1.dll  microtex-qt-example.exe  microtex-qt-example.exe.p
> 
> User.PC@APP-BUILDER UCRT64 ~/Development/tst/MicroTeX/build/example/qt
> $ ./microtex-qt-example.exe
> Required arguments:
>   <clm data file\>
>   <math font file\>
>   <samples file\>
> Optional arguments:
>   <if render glyph use path: true|false>
>   <if render use skia: true|false>
> 
> User.PC@APP-BUILDER UCRT64 ~/Development/tst/MicroTeX/build/example/qt
> $
> $ ./microtex-qt-example.exe FiraMath-Regular.clm2 FiraMath-Regular.otf SAMPLES.tex

![Microtex-Openmath-branch-Qt6-Win10-FiraMath-Meson](https://github.com/user-attachments/assets/be17dcbd-df87-4625-9317-2d09a75c5ea6)

It may be all work because now used Qt library that compiled with `-static-libgcc -static-libstdc++` and mingw library doesn't needed
