### ISSUE TITLE
Build error with Cywin64

### ISSUE THREAD

**Issue by blackStar1314** [NanoMichael/cLaTeXMath#181]
Build detail:
![image](https://github.com/user-attachments/assets/6b0861f7-1fbd-4641-af10-0c04ec019d45)

soruce position:
https://github.com/NanoMichael/MicroTeX/blob/0e3707f6dafebb121d98b53c64364d16fefe481d/src/fonts/font_info.cpp#L99

why _b = "�" when string to wstring?

**Comment by NanoMichael** [comment]
Please consider using the `openmath` branch

**Comment by blackStar1314** [comment]
OK！Thanks.
