### ISSUE TITLE
Character '&' is only available in array mode!

### ISSUE THREAD

**Issue by igormironchik** [NanoMichael/cLaTeXMath#185]
Not sure what it is. So better to ask you. A following LaTeX math

```latex
\begin{align*}a&=b+c\\d+e&=f\end{align*}
```

throws exception

```
Character '&' is only available in array mode!
```

**Comment by sp1ritCS** [comment]
This is due to the way the parser works. `align*` is just not implemented. You could use `align` (it also doesn't number equations) or implement it.

**Comment by igormironchik** [comment]
I won't do PR. I have my own tasks. Ok. I understand you. Thank you.
