### ISSUE TITLE
licensing

### ISSUE THREAD

**Issue by toookan** [NanoMichael/cLaTeXMath#2]
Hello @NanoJeoMichael ,

could you please specify the [licensing](https://help.github.com/articles/licensing-a-repository/)? 
If you do not specify licensing, no-one can use/fork your project legally.

Thank you

**Comment by NanoMichael** [comment]
I'm too lazy to even specify a license :joy: . Since the project can help somebody, I'll do it right now.

**Comment by toookan** [comment]
Understand, I'm lazy too 😃 
Thanks :+1:

**Comment by NanoMichael** [comment]
@toookan Actually I changed the name of this project from `C_TeX` into `cLaTexMath`. I suggest you use this project instead of the project you originally used, I've been fixed many bugs.
