### ISSUE TITLE
Use macro instead of configure file

### ISSUE THREAD

**Issue by Xrysnow** [NanoMichael/cLaTeXMath#49]
In #48, a configure file is added for compatibility with older gcc. But this can be done through macro `__GNUC__`. Use the macro is more portable for cross compiling and embedding.

**Comment by sp1ritCS** [comment]
> the macro is more portable for cross compiling and embedding.

I don't think so, as `__GNUC__` is limited to gcc. In theory the EXPERIMENTAL_FS global can be expanded to older versions of other compilers beside gcc (clang or msvc) that carry std::filesystem in std::experimental::filesystem

**Comment by Xrysnow** [comment]
Well, if you do need c++17 feature, old compiler should not be used at all. I think fallback to c++11 is much better than using `std::experimental` here.

**Comment by sp1ritCS** [comment]
> Well, if you do need c++17 feature, old compiler should not be used at all
Yes, I totally agree - But my goal is, that Leap 15.2 (that still carries gcc 7.5.0) has the latest featureset. Same for github. As long as ubuntu-latest is still 18.04 (also gcc 7.5.0) it should have the full featureset.

> I think fallback to c++11 is much better
How do you imagine to fallback c++11, that doesn't support std::filesystem? Because I don't think that cLaTeXMath should depend on boostlib, which would be the obvious alternative.

**Comment by Xrysnow** [comment]
It's easy to replace current `std::filesystem` usage with string operation and C file functions.
For example, here:
https://github.com/NanoMichael/cLaTeXMath/blob/90c192eaa8b6958e1619939f65cb5a65088313a0/src/latex.cpp#L50-L55
can be replaced by
```cpp
std::string path = paths.front();
std::string file = path + "/.clatexmath-res_root";
FILE* fp = fopen(file.c_str(), "rb");
if(fp) {
	fclose(fp);
	return path;
}
```
when c++17 is not supported.

**Comment by sp1ritCS** [comment]
> ```c++
> std::string path = paths.front();
> std::string file = path + "/.clatexmath-res_root";
> FILE* fp = fopen(file.c_str(), "rb");
> if(fp) {
> 	fclose(fp);
> 	return path;
> }
> ```
> 
> when c++17 is not supported.

I  don't know much about c/++. The current implementation is just a rewrite of my rust implementation of the XDG_DATA_* / FHS spec, based mostly from copied code from stackoverflow or other git repos.

Feel free to create a merge request with this.

**Comment by Xrysnow** [comment]
OK, I will create a PR about it later.
