### ISSUE TITLE
【HELP】你好！如何在iOS设备上使用呢？

### ISSUE THREAD

**Issue by gongandy** [NanoMichael/cLaTeXMath#5]
你好，这个库写的很棒，请问如何集成到iOS使用呢？

**Comment by NanoMichael** [comment]
你好，我对 iOS 开发不是很了解，如果你想集成到 iOS 使用，我可以提供一些建议。首先你需要实现 [graphic.h](https://github.com/NanoMichael/cLaTeXMath/blob/master/src/graphic/graphic.h) 文件里定义的所有虚类，包括 `Font`，`TextLayout` 以及 `Graphics2D` 这几个接口；以及你需要实现在这几个类里定义的几个静态函数；这些工作都做完之后，可以按照文档进行使用。

欢迎提交 PR 和 issure。
