### ISSUE TITLE
SEGV when rendering LaTeX

### ISSUE THREAD

**Issue by sp1ritCS** [NanoMichael/cLaTeXMath#53]
The string
```
$\left(\frac{a}{a}\right-)$
```
causes cLaTeXMath to segfault instead of the usual SIGTRAP when it has issues rendering latex.

See: https://github.com/blackhole89/notekit/issues/80

**Comment by NanoMichael** [comment]
The current workaround is just to ignore the invalid delimiters, such issue will be fixed when migrating to 'Unicode-math' was done.
