### ISSUE TITLE
Is cLaTeXMath violating the GPL?

### ISSUE THREAD

**Issue by LyesSaadi** [NanoMichael/cLaTeXMath#59]
So... Who isn't excited from some licensing fun (: ?

Anyway... I'm trying to package cLaTeXMath for Fedora... The package have been approved for ~1.5 week and I still haven't even imported it into the Fedora Git. Why ? Because of Licensing (: ...

So, it seems that cLaTeXMath is a rewrite of jlatexmath in C.

To my (very) limited understanding of copyright law, cLaTeXMath is violating the GPL in three ways... Let's review them, shall we?

# The issues

1. **Font licenses:** So, thanks to eclipseo (a Fedora contributor who reviewed the package, and, honestly, a heavenly gift sent upon this cursed land) cLaTeXMath gets its fonts from jlatexmath... jlatexmath breaks down the licenses of each font, and cLaTeXMath has respected this breakdown wonderfully and provided all the licenses (thank you for that :D). BUT, in jlatexmath some fonts have... No license specified? It would be assumed then that those licenses are under GPL... Which... Would be weird, but whatever. Those fonts are the cyrillic and greek ones as well as `special.ttf`. I have opened a ticket upstream to try and clear up things, but nothing yet (if you have any clue, I'd be happy to know it !)...
2. **XML files:** Anyway, even if those fonts are not under GPL, there is another problem: the xml files for the cyrillic and greek fonts definitely are though, as they seem to gave been created by the jlatexmath devs (btw, are those really needed?).
3. **Rewriting of a GPL project:** I discovered this one entirely by chance ^.^, and it actually is the one that pushed me to create this ticket right now as for the fonts one I was waiting for the jlatexmath answer. Anyway, [according to the gnu.org GPL FAQ](https://www.gnu.org/licenses/gpl-faq.en.html#TranslateCode), when we rewrite a GPL code under a new programming language, it also needs to be GPL! Though, I am not confident about this one. Is cLaTeXMath really a rewrite of jlatexmath or just a program doing the same thing in a different programming language? Where is the line between those two? I have no idea, and this is making me MAD.

# What should be done

1. Adding a breakdown similar to jlatexmath's describing in details which font file is under which license to maybe help future helpless packager souls which may enter this cursed words of font licenses and help them through their quest.
2. Adding the GPL to the fonts licenses if the xml files are needed.
3. Eventually adding new licenses when the jlatexmath project finally answers my helpless plead for forgiveness upon my soul for having dared to decipher legalese.
4. ~~Sacrifice lawyers to the all mighty GPL god and pray for its benevolence.~~
5. Relicense cLaTeXMath to the GPL if it indeed is a rewrite of the jlatexmath project. That should not be an issue since the MIT license is compatible with the GPL license (no need to ask for every contributor's agreement).

# Conclusion

Copyright laws are annoying and let's blame the British for that.

**Comment by NanoMichael** [comment]
This project was written with reference to the awesome project jlatexmath originally, I'm now migrating from the PLAIN-OLD-TEX to the Unicode-math to support modern LaTeX like XeTeX and LuaLaTeX (branch [openmath](https://github.com/NanoMichael/cLaTeXMath/tree/openmath)), the _master_ branch will be deprecated after this work has been done, so the font and the XML resources will be removed. Maybe the _openmath_ version could use the MIT license and the _master_ use the GPL?

**Comment by LyesSaadi** [comment]
Oh, I see, I've missed that branch!

> Maybe the openmath version could use the MIT license and the master use the GPL?
As stated previously, I'm not a lawyer, and I may not be the best place for advice. But my best guess is that if the new branch does not have the same purpose/functionality as the original jlatexmath, it's no longer a rewrite and no longer a modification of the original work?

**Comment by LyesSaadi** [comment]
> This project was written with reference to the awesome project jlatexmath originally, I'm now migrating from the PLAIN-OLD-TEX to the Unicode-math to support modern LaTeX like XeTeX and LuaLaTeX (branch openmath), the master branch will be deprecated after this work has been done, so the font and the XML resources will be removed. Maybe the openmath version could use the MIT license and the master use the GPL?

Now that I think of it, I never really asked the question. Is cLaTeXMath really a rewrite of jlatexmath: Does it use the same logic in its rendering? Or is it just a name reference?

**Comment by NanoMichael** [comment]
@LyesSaadi Sorry for the late response 😅 . No, it is not a rewrite of the jlatexmath, but inspired by it and use the XML resources from the jlatexmath project. The rendering logic is completely different from the jlatexmath project.

**Comment by LyesSaadi** [comment]
In that case, if it only shares the name, and it is not a rewrite, I do not think the GPL copyright should stick, and master could still be under MIT. The XML files still need the GPL with them though (and the font files which do not have any license explained, provided they are indeed under GPL)...

**Comment by NanoMichael** [comment]
When the `openmath` version released,  the XML files will be removed, that should not be a problem. I'll add the GPL license into the XML resources folder.

**Comment by NanoMichael** [comment]
The licenses were added, please check out `res/greek/LICENSE` and `res/cyrillic/LICENSE`.

**Comment by LyesSaadi** [comment]
Thank you! I still have to wait for jlatexmath to give me the unknown font licenses before pushing this to Fedora repositories though :).

Anyway, thank you for taking care of this :) !
