### ISSUE TITLE
compile error in macro_def.cpp

### ISSUE THREAD

**Issue by Xrysnow** [NanoMichael/cLaTeXMath#6]
The macro `mac` in `core/macro_def.cpp` dosen't work well in VS and will give compile error.

> 错误	C2440	“初始化”: 无法从“initializer list”转换为“std::map<std::wstring,tex::MacroInfo *,std::less<_Kty>,std::allocator<std::pair<const _Kty,_Ty>>>”

**Comment by NanoMichael** [comment]
Dose your compiler support c++ 11?

**Comment by Xrysnow** [comment]
I'm using VS2017 and it supports c++11. The compiler can't expand macro `mac` to the right one. There will be no error after replace `mac` by `mac3` and `mac4`.

**Comment by NanoMichael** [comment]
I see... MSVC's preprocessor seems to behave quite differently from the standard specification. It does not support expand `__VA_ARGS__`, I recommend using g++ instead.
