### ISSUE TITLE
cross "platformnes" of the cairo/gtk version

### ISSUE THREAD

**Issue by sp1ritCS** [NanoMichael/cLaTeXMath#65]
Hi Nano,

we are currently working on getting [NoteKit](https://github.com/blackhole89/notekit) on as many as possible distros / OS's working. As we depend on cLaTeXMath we have also created packages (and patches) for it.

[home:sp1rit:testing:notekit/clatexmath](https://build.opensuse.org/package/show/home:sp1rit:testing:notekit/clatexmath) builds deb packages for Debian and Ubuntu, rpm's for *SUSE, Fedora, Mageia & CentOS, and .pkg.tar.zst for Arch. I think the Debian copyright file (within the debian.tar.xz) should get updated to explicitly mention  the licenses from the fonts (and those xml files :D)

[home:sp1rit:mingw/mingw-clatexmath](https://build.opensuse.org/package/show/home:sp1rit:mingw/mingw-clatexmath) build x86_64 and i686 mingw dlls for use in fedora's mingw space that we use to [automatically nightly build notekit](https://github.com/blackhole89/notekit/blob/master/.github/workflows/windows.yml) for Windows. However building cLaTeXMath on MinGW some issues.  
First M_PI is not supported and has to be replaced with the G_PI constant: [use_glib_pi_const.diff](https://build.opensuse.org/package/view_file/home:sp1rit:mingw/mingw-clatexmath/use_glib_pi_const.diff?expand=1)

Also on newer versions of some *mm package (I think it was pangomm) that fedora 34 carries, the way symbols are exposed on windows changed and that caused clatexmath to stop building. @LyesSaadi solution was just to remove the samples since the offending line was in there (afaik Pango::Init) in the spec file:
```
rm -rf src/samples/
sed -i '99,104d' meson.build
sed -i '163,167d' meson.build
```

However that also affects our notekit build on anything newer than f33, until the bug is fixed.

Also regarding MinGW, if you run clatexmath within native MinGW on Windows, the `LaTeX::queryResourceLocation(` is unable to detect /mingw64/share/clatexmath because it's wraped in an `#ifndef _WIN32` by @Xrysnow .

The block 
```cpp
char* xdg = getenv("XDG_DATA_DIRS");
  if (xdg != NULL && strcmp(xdg, "") != 0) {
    stringstream xdg_paths(xdg);
    string xdg_path;
    while (getline(xdg_paths, xdg_path, ':')) {
      paths.push(xdg_path);
    }
  }
```
would have to be moved of of the ifndef block in order for it to work.

On OS X I have a homebrew tap setup here [@sp1ritCS/homebrew-tap](https://github.com/sp1ritCS/homebrew-tap/), so if you have homebrew installed you can simply type brew install sp1ritCS/tap/clatexmath.

**Comment by PikachuHy** [comment]
Have you tried compiling on MSVC?

**Comment by NanoMichael** [comment]
Thank you very much for your contributions to this project.

> I think the Debian copyright file (within the debian.tar.xz) should get updated to explicitly mention the licenses from the fonts (and those xml files :D)

I'll add the licenses soon.

Because I'm very busy at present, I don't have much time to maintain this project :sweat_smile: (actually, the development for uni-math support was halted by now). If you have any PR, that is very appreciated.

**Comment by sp1ritCS** [comment]
> Have you tried compiling on MSVC?

No, I do not have any microsoft compiler toolchain installed. Also, as you can see from the gh action, our windows built is cross-compiled from fedora 33 mingw. 

> If you have any PR, that is very appreciated.

will do
