### ISSUE TITLE
link error in msvc

### ISSUE THREAD

**Issue by Xrysnow** [NanoMichael/cLaTeXMath#7]
Fake inline functions will cause link error in msvc.
https://github.com/NanoMichael/cLaTeXMath/blob/3caa16d60bef9018c70b1dadf29a45b39de2c665/src/fonts/fonts.h#L364
https://github.com/NanoMichael/cLaTeXMath/blob/3caa16d60bef9018c70b1dadf29a45b39de2c665/src/fonts/fonts.cpp#L250
https://github.com/NanoMichael/cLaTeXMath/blob/3caa16d60bef9018c70b1dadf29a45b39de2c665/src/fonts/fonts.h#L423
适配一下msvc不行吗？

**Comment by Xrysnow** [comment]
还有漫天飞舞的
`warning C4290: 忽略 C++ 异常规范，但指示函数不是 __declspec(nothrow)`
C++11就弃用的特性了：https://zh.cppreference.com/w/cpp/language/except_spec

**Comment by NanoMichael** [comment]
这块代码比较老了，很多代码写得不规范，也没有更改这些代码。目前我手头没有 Windows 系统的电脑，要 996，所以没有很多时间来维护这个项目，有时间我整体支持一下 MSVC。欢迎提各种 PR。
