### ISSUE TITLE
Unrecognized environment: equation

### ISSUE THREAD

**Issue by PikachuHy** [NanoMichael/cLaTeXMath#71]
```
\begin{equation}
  L(Y, f(X))=\left\{
  	\begin{aligned}
  	1, \quad Y \neq f(X)\\
  	0, \quad Y = f(X)\\
  	\end{aligned}
  	\right
  	.
  \end{equation}

```
expect:
![image](https://user-images.githubusercontent.com/18223871/118295691-c0939880-b50e-11eb-9be1-5085a53bdb6d.png)
actual:
![image](https://user-images.githubusercontent.com/18223871/118295807-d4d79580-b50e-11eb-8f19-35152c2b2d58.png)

**Comment by NanoMichael** [comment]
Currently, the `equation` environment is not supported. The `equation` requires to show its _number_, but for this project, it is impossible (because these equations are separated in context). 

Anyway, I'll make a PR to support the `equation` environment but will not show its number.
