### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by blackhole89** [NanoMichael/cLaTeXMath#9]
Great project! I notice there is currently no word on the license in the repository. It would be great if you could make it available under GPL or something compatible with it, since it appears to be a perfect match for [my markdown notetaking program](https://github.com/blackhole89/notekit) (which currently uses the abandoned and buggy [Lasem](https://wiki.gnome.org/Projects/Lasem) for rendering LaTeX instead).

**Comment by NanoMichael** [comment]
I got it. Because of this project contains some resources under different licenses (check out the directory `res/fonts/license`), I don't know how to choose a proper license for this project. Any suggestions?

**Comment by blackhole89** [comment]
I think the standard approach would be to just slap a license of your choice on the source code and put it in the root folder, and then maybe place a remark saying that parts of the software are covered by different licenses in the README.

**Comment by NanoMichael** [comment]
Thank you for your advice, I'll add the license soon.

**Comment by NanoMichael** [comment]
@blackhole89 The license was added, please check it out.

**Comment by lazingor** [comment]
I agree: great project! Would you consider applying an LGPL or MIT licence, since it's being designed as a library? I was thinking of trying to figure out how to use the project in a mobile app, but I wouldn't be able to do that under GPL as then the whole app would have to fall under GPL, if I understand things correctly.

**Comment by NanoMichael** [comment]
@lazingor Well, I'm not familiar with the open-source licensing 😅. After some dig in, I realize that the GPL license has too many limitations, maybe the MIT license is a better choice. I'll change it soon.

**Comment by lazingor** [comment]
@NanoMichael That's great! Gonna get stuck in to experimenting.
