### ISSUE TITLE
Support blank character?

### ISSUE THREAD

**Issue by James-mathpresso** [NanoMichael/cLaTeXMath#91]
Dose this latex support blank character?

[Input]
What is result

[Result]
Whatisresult

![스크린샷 2022-01-12 오후 2 04 55](https://user-images.githubusercontent.com/76418896/149067177-418845c0-cf4d-4c40-83a8-3ebc952458b5.png)

**Comment by sp1ritCS** [comment]
you need `\text{What is [the] result}`
